### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by jasper12123** [LiTianYu6/NerveStitcher#1]
Traceback (most recent call last):
  File "E:/Source_Code/python/NerveStitcher-master/stitching.py", line 61, in <module>
    matching = Matching(config).eval().to(device)
  File "E:\Source_Code\python\NerveStitcher-master\models\matching.py", line 53, in __init__
    self.superpoint = SuperPoint(config.get('superpoint', {}))
  File "E:\Source_Code\python\NerveStitcher-master\models\superpoint.py", line 137, in __init__
    self.load_state_dict(torch.load(str(path)))
  File "D:\shaki\Anaconda3\envs\tensorflow2.4\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\shaki\Anaconda3\envs\tensorflow2.4\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by LiTianYu6** [comment]
This may be a problem caused by the model. I noticed the problem and have modified it.

**Comment by jasper12123** [comment]
> 这可能是模型导致的问题。我注意到了这个问题并对其进行了修改。

I am sorry that the modified project is still this problem, please because the project uses git lfs, so you need to use lfs to download the source code ?

**Comment by LiTianYu6** [comment]
> 

While git-lfs can sometimes corrupt files, I don't think it's causing the problem here.
Maybe due to the PyTorch version, I use PyTorch=1.7.0 and it works fine.

**Comment by LiTianYu6** [comment]
> > 这可能是模型导致的问题。我注意到了这个问题并对其进行了修改。
> 
> I am sorry that the modified project is still this problem, please because the project uses git lfs, so you need to use lfs to download the source code ?

After testing, it is indeed a problem with git-lfs. I will upload the models to an external link later. 
Thanks for your question!

**Comment by LiTianYu6** [comment]
> > 这可能是模型导致的问题。我注意到了这个问题并对其进行了修改。
> 
> I am sorry that the modified project is still this problem, please because the project uses git lfs, so you need to use lfs to download the source code ?

Here is the download link for WEIGHTS: https://drive.google.com/drive/folders/1SgHwGcFwKbV6Bv7OgV1PbqCWmSJgx3jZ?usp=sharing
